/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ISwapRouter {
      
    export type ExactInputSingleParamsStruct = {tokenIn: AddressLike, tokenOut: AddressLike, fee: BigNumberish, recipient: AddressLike, deadline: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, sqrtPriceLimitX96: BigNumberish}

    export type ExactInputSingleParamsStructOutput = [tokenIn: string, tokenOut: string, fee: bigint, recipient: string, deadline: bigint, amountIn: bigint, amountOutMinimum: bigint, sqrtPriceLimitX96: bigint] & {tokenIn: string, tokenOut: string, fee: bigint, recipient: string, deadline: bigint, amountIn: bigint, amountOutMinimum: bigint, sqrtPriceLimitX96: bigint }
  
    }

  export interface MockUniswapV3RouterInterface extends Interface {
    getFunction(nameOrSignature: "exactInputSingle" | "multiplierBps"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'exactInputSingle', values: [ISwapRouter.ExactInputSingleParamsStruct]): string;
encodeFunctionData(functionFragment: 'multiplierBps', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'exactInputSingle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiplierBps', data: BytesLike): Result;
  }

  

  export interface MockUniswapV3Router extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockUniswapV3Router;
    waitForDeployment(): Promise<this>;

    interface: MockUniswapV3RouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    exactInputSingle: TypedContractMethod<
      [params: ISwapRouter.ExactInputSingleParamsStruct, ],
      [bigint],
      'payable'
    >
    

    
    multiplierBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'exactInputSingle'): TypedContractMethod<
      [params: ISwapRouter.ExactInputSingleParamsStruct, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'multiplierBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }