/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockDexAdapterInterface extends Interface {
    getFunction(nameOrSignature: "executeSwap" | "multiplierBps"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'executeSwap', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'multiplierBps', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'executeSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiplierBps', data: BytesLike): Result;
  }

  

  export interface MockDexAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockDexAdapter;
    waitForDeployment(): Promise<this>;

    interface: MockDexAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    executeSwap: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, arg3: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    multiplierBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'executeSwap'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, arg3: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'multiplierBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }