/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockFlashLenderInterface extends Interface {
    getFunction(nameOrSignature: "flashLoanSimple" | "premiumBps"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'flashLoanSimple', values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'premiumBps', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'flashLoanSimple', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'premiumBps', data: BytesLike): Result;
  }

  

  export interface MockFlashLender extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockFlashLender;
    waitForDeployment(): Promise<this>;

    interface: MockFlashLenderInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    flashLoanSimple: TypedContractMethod<
      [receiverAddress: AddressLike, asset: AddressLike, amount: BigNumberish, params: BytesLike, arg4: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    premiumBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'flashLoanSimple'): TypedContractMethod<
      [receiverAddress: AddressLike, asset: AddressLike, amount: BigNumberish, params: BytesLike, arg4: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'premiumBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }