/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockUniswapV2RouterInterface extends Interface {
    getFunction(nameOrSignature: "multiplierBps" | "swapExactTokensForTokens"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'multiplierBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapExactTokensForTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'multiplierBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactTokensForTokens', data: BytesLike): Result;
  }

  

  export interface MockUniswapV2Router extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockUniswapV2Router;
    waitForDeployment(): Promise<this>;

    interface: MockUniswapV2RouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    multiplierBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swapExactTokensForTokens: TypedContractMethod<
      [amountIn: BigNumberish, arg1: BigNumberish, path: AddressLike[], to: AddressLike, arg4: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'multiplierBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapExactTokensForTokens'): TypedContractMethod<
      [amountIn: BigNumberish, arg1: BigNumberish, path: AddressLike[], to: AddressLike, arg4: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }