/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IDexAdapter, IDexAdapterInterface } from "../../interfaces/IDexAdapter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenIn",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "tokenOut",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "routeData",
        "type": "bytes"
      }
    ],
    "name": "executeSwap",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "amountOut",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IDexAdapter__factory {
    static readonly abi = _abi;
    static createInterface(): IDexAdapterInterface {
      return new Interface(_abi) as IDexAdapterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IDexAdapter {
      return new Contract(address, _abi, runner) as unknown as IDexAdapter;
    }
  }
  