/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FlashLoanExecutorInterface extends Interface {
    getFunction(nameOrSignature: "executeOperation" | "lender" | "owner" | "requestFlashLoan"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ArbitrageExecuted" | "FlashLoanRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'executeOperation', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'lender', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestFlashLoan', values: [AddressLike, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'executeOperation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestFlashLoan', data: BytesLike): Result;
  }

  
    export namespace ArbitrageExecutedEvent {
      export type InputTuple = [asset: AddressLike, amountBorrowed: BigNumberish, amountRepaid: BigNumberish, profit: BigNumberish];
      export type OutputTuple = [asset: string, amountBorrowed: bigint, amountRepaid: bigint, profit: bigint];
      export interface OutputObject {asset: string, amountBorrowed: bigint, amountRepaid: bigint, profit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FlashLoanRequestedEvent {
      export type InputTuple = [asset: AddressLike, amount: BigNumberish];
      export type OutputTuple = [asset: string, amount: bigint];
      export interface OutputObject {asset: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FlashLoanExecutor extends BaseContract {
    
    connect(runner?: ContractRunner | null): FlashLoanExecutor;
    waitForDeployment(): Promise<this>;

    interface: FlashLoanExecutorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    executeOperation: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, premium: BigNumberish, initiator: AddressLike, params: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    lender: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    requestFlashLoan: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, params: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'executeOperation'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, premium: BigNumberish, initiator: AddressLike, params: BytesLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lender'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requestFlashLoan'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, params: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ArbitrageExecuted'): TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
getEvent(key: 'FlashLoanRequested'): TypedContractEvent<FlashLoanRequestedEvent.InputTuple, FlashLoanRequestedEvent.OutputTuple, FlashLoanRequestedEvent.OutputObject>;

    filters: {
      
      'ArbitrageExecuted(address,uint256,uint256,uint256)': TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
      ArbitrageExecuted: TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
    

      'FlashLoanRequested(address,uint256)': TypedContractEvent<FlashLoanRequestedEvent.InputTuple, FlashLoanRequestedEvent.OutputTuple, FlashLoanRequestedEvent.OutputObject>;
      FlashLoanRequested: TypedContractEvent<FlashLoanRequestedEvent.InputTuple, FlashLoanRequestedEvent.OutputTuple, FlashLoanRequestedEvent.OutputObject>;
    
    };
  }