/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'FlashLoanExecutor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FlashLoanExecutor__factory>
getContractFactory(name: 'OneInchAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OneInchAdapter__factory>
getContractFactory(name: 'UniswapV3Adapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV3Adapter__factory>
getContractFactory(name: 'UniswapV2Adapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV2Adapter__factory>
getContractFactory(name: 'IDexAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IDexAdapter__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'IFlashLoanSimpleReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFlashLoanSimpleReceiver__factory>
getContractFactory(name: 'IPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPool__factory>
getContractFactory(name: 'ISwapRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISwapRouter__factory>
getContractFactory(name: 'IUniswapV2RouterLike', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2RouterLike__factory>
getContractFactory(name: 'SafeERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafeERC20__factory>
getContractFactory(name: 'MockDexAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockDexAdapter__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockOneInchRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockOneInchRouter__factory>
getContractFactory(name: 'MockFlashLender', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockFlashLender__factory>
getContractFactory(name: 'MockUniswapV2Router', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUniswapV2Router__factory>
getContractFactory(name: 'MockUniswapV3Router', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUniswapV3Router__factory>

  getContractAt(name: 'FlashLoanExecutor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FlashLoanExecutor>
getContractAt(name: 'OneInchAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OneInchAdapter>
getContractAt(name: 'UniswapV3Adapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV3Adapter>
getContractAt(name: 'UniswapV2Adapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV2Adapter>
getContractAt(name: 'IDexAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IDexAdapter>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'IFlashLoanSimpleReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFlashLoanSimpleReceiver>
getContractAt(name: 'IPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPool>
getContractAt(name: 'ISwapRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISwapRouter>
getContractAt(name: 'IUniswapV2RouterLike', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2RouterLike>
getContractAt(name: 'SafeERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafeERC20>
getContractAt(name: 'MockDexAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockDexAdapter>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockOneInchRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockOneInchRouter>
getContractAt(name: 'MockFlashLender', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockFlashLender>
getContractAt(name: 'MockUniswapV2Router', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUniswapV2Router>
getContractAt(name: 'MockUniswapV3Router', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUniswapV3Router>

  deployContract(name: 'FlashLoanExecutor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FlashLoanExecutor>
deployContract(name: 'OneInchAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OneInchAdapter>
deployContract(name: 'UniswapV3Adapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV3Adapter>
deployContract(name: 'UniswapV2Adapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Adapter>
deployContract(name: 'IDexAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDexAdapter>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IFlashLoanSimpleReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFlashLoanSimpleReceiver>
deployContract(name: 'IPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPool>
deployContract(name: 'ISwapRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISwapRouter>
deployContract(name: 'IUniswapV2RouterLike', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2RouterLike>
deployContract(name: 'SafeERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeERC20>
deployContract(name: 'MockDexAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockDexAdapter>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockOneInchRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockOneInchRouter>
deployContract(name: 'MockFlashLender', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockFlashLender>
deployContract(name: 'MockUniswapV2Router', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV2Router>
deployContract(name: 'MockUniswapV3Router', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Router>

  deployContract(name: 'FlashLoanExecutor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FlashLoanExecutor>
deployContract(name: 'OneInchAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OneInchAdapter>
deployContract(name: 'UniswapV3Adapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV3Adapter>
deployContract(name: 'UniswapV2Adapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Adapter>
deployContract(name: 'IDexAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDexAdapter>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IFlashLoanSimpleReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFlashLoanSimpleReceiver>
deployContract(name: 'IPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPool>
deployContract(name: 'ISwapRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISwapRouter>
deployContract(name: 'IUniswapV2RouterLike', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2RouterLike>
deployContract(name: 'SafeERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeERC20>
deployContract(name: 'MockDexAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockDexAdapter>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockOneInchRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockOneInchRouter>
deployContract(name: 'MockFlashLender', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockFlashLender>
deployContract(name: 'MockUniswapV2Router', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV2Router>
deployContract(name: 'MockUniswapV3Router', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Router>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  