/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDexAdapter } from './IDexAdapter.js';
export type { IERC20 } from './IERC20.js';
export type { IFlashLoanSimpleReceiver } from './IFlashLoanSimpleReceiver.js';
export type { IPool } from './IPool.js';
export type { ISwapRouter } from './ISwapRouter.js';
export type { IUniswapV2RouterLike } from './IUniswapV2RouterLike.js';